language:
  python
python:
  - 2.6
  - 2.7
  - 3.3
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage coveralls --use-mirrors
script:
  nosetests --with-coverage --cover-package=triplesec --verbose
notifications:
  email:
    - filippo.valsorda@gmail.com
after_success:
  coveralls
