language:
  python
python:
  - 2.6
  - 2.7
  - 3.3
install:
  - pip install -e .
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
script:
  nosetests --verbose
notifications:
  email:
    - filippo.valsorda@gmail.com
after_success:
  - pip install coveralls
  - coverage run --source=triplesec setup.py -q nosetests
  - coveralls
